name: very_good_test_runner
description: A test runner for Flutter and Dart created by Very Good Ventures
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
